### ISSUE TITLE
No module named cryptography.fernet

### ISSUE THREAD

**Issue by sparta34** [1captainnemo1/Powershell_Fernet_Obfuscator#1]
hi bro thanks for this great tool , but when i try to execute the final payload i get this error No module named cryptography.fernet

**Comment by 1captainnemo1** [comment]
On windows , by default python doesnt have fernet installed. 
thus when you have to rin the tool . you need to 
pip install crytography
pip install cryptography.fernet
pip install Fernet 

The second command might not hit home base bit the rest will do the job perfectly.
In my fernet_onfuscator project, I have solved the issue by turning the .py file to .exe, with all the dependencies preinstalled.

I plan to do the same on this , once i have some time.
Till then this should resolve the issue and I am considering this issue closed.
If youface any further issues , please raise it here
Thanks 
#Captain_Nemo

**Comment by sparta34** [comment]
thanks for the replay but i still can't get cryptography.fernet installed i tried with python 2.7 and python 3.7!! any idea 

C:\Python27amd64>pip install cryptography.fernet
Collecting cryptography.fernet
  ERROR: Could not find a version that satisfies the requirement cryptography.fernet (from versions: none)
ERROR: No matching distribution found for cryptography.fernet
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
